config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

  resources :users
  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/failed_login_attempt.rb
class FailedLoginAttempt < ActiveRecord::Base

end

app/models/throttle.rb
class Throttle

  def clear?(user)
    user && !user.is_locked_out?
  end

  def update_failures_status(user)
    user.failed_login_attempts.create!(time_failed: DateTime.now) if user
    if !user || user.has_more_tries?
      'Incorrect email/password combo'
    elsif user.is_locked_out? || user.failures_in_time?
      user.update_attributes(locked_out_at: DateTime.now) unless user.is_locked_out?
      'You are locked out. Please try again later.'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: {minimum: 8}, :on => :create
  validates :password, confirmation: true

  validates :email, uniqueness: true

  has_many :failed_login_attempts


  def failures_in_time?(minutes=5, times=3)
    time_difference = failed_login_attempts.last.time_failed - failed_login_attempts[-times].time_failed
    time_difference < minutes.minutes
  end

  def is_locked_out?(locked_out_time=10)
    return false if locked_out_at.nil?
    diff = TimeDifference.between(Time.now, locked_out_at).in_minutes
    diff <= locked_out_time ? true : reset_lock_out
  end

  def reset_lock_out
    locked_out_at = nil
    false
  end

  def has_more_tries?(times=3)
    (failed_login_attempts.length < times || !failures_in_time?) && !is_locked_out?
  end

  def reset_failed_attempts
    failed_login_attempts.destroy_all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index

  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    throttle = Throttle.new

    if throttle.clear?(user) && (@user = login(params[:email], params[:password]))
      @user.reset_failed_attempts
      redirect_to(root_path, notice: 'Successfully logged in!')
    else
      flash[:notice] = throttle.update_failures_status(user)
      render :new
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Successfully logged out!')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Successfully Registered!'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
<h3 class="text-center">Welcome to Fake App!</h3>

<% unless logged_in? %>
  <p class="text-center">You are not logged in</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FakeApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul class="nav nav-tabs" role="tablist">
  <% if logged_in? %>
    <li><%= link_to 'Logout', logout_path, method: :post %></li>
  <% else %>
    <li><%= link_to 'Register', new_user_path %></li>

    <li><%= link_to 'Login', login_path %></li>
  <% end %>
  </ul>
</nav>

<div>
  <p class="alert text-center"><%= flash[:notice] %></p>
</div>

<%= yield %>

</body>
</html>

app/views/user_sessions/new.html.erb
<h3 class="text-center">Please Login Below</h3>

<div class="col-sm-6 col-sm-offset-3">

  <%= form_tag user_sessions_path, method: :post, class: 'form-horizontal', role: 'form' do %>

    <div class="form-group">
      <%= label_tag :email, nil, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= email_field_tag :email, nil, class: "col-sm-2 form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :password, nil, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= password_field_tag :password, nil, class: "col-sm-2 form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= submit_tag "Login", name: nil, class: "btn btn-default" %>
      </div>
    </div>

  <% end %>

</div>

app/views/users/new.html.erb
<h3 class="text-center">Please Register Below</h3>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |error| %>
    <p class="text-center alert"><%= error %></p>
  <% end %>
<% end %>

<div class="col-sm-6 col-sm-offset-3">

  <%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>

    <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.email_field :email, class: "col-sm-2 form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: "col-sm-2 form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.password_field :password_confirmation, class: "col-sm-2 form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Register", class: "btn btn-default" %>
      </div>
    </div>

  <% end %>

</div>